language: go
go:
- 1.7.x
before_install:
- go get github.com/mattn/goveralls
install:
- go get github.com/stretchr/testify
script:
- $HOME/gopath/bin/goveralls -service=travis-ci
before_deploy:
- env GOOS=linux   GOARCH=386   go build -o bin/churn-linux-x86-$TRAVIS_TAG       src/churn.go
- env GOOS=linux   GOARCH=amd64 go build -o bin/churn-linux-x64-$TRAVIS_TAG       src/churn.go
- env GOOS=darwin  GOARCH=386   go build -o bin/churn-mac-x86-$TRAVIS_TAG         src/churn.go
- env GOOS=darwin  GOARCH=amd64 go build -o bin/churn-mac-x64-$TRAVIS_TAG         src/churn.go
- env GOOS=windows GOARCH=386   go build -o bin/churn-windows-x86-$TRAVIS_TAG.exe src/churn.go
- env GOOS=windows GOARCH=amd64 go build -o bin/churn-windows-x64-$TRAVIS_TAG.exe src/churn.go
deploy:
  provider: releases
  api_key:
    secure: "mWhgSSn76qxshKP58SOst6wECTVqFzaT634Be7YV6Rqs2SPp0QMSBYPRL8MDUhlSC3hXb28LHbWV7zZGLGOv9tBY7ZKpKg49Mz5jekROM56S/0Zj9crHm2msCU8qijqCGYBs5v/9IxwyZvbXontBAsoN9zHMvksVrwqZtO3ymCYDZgq6+qVYZ0QNji5UPRjnOskcjTS0GuDNAmHklV+5ldDo5XvTNCLRiYbjaOoRKuUnQ2PY7qosHNfehlE4nOZlrsG/o9ZDjKKDCmpX83vX4SuqrWyGZyGLOo/76BIHYxhZNoCjtQCn5rTTg3SM/3xIaR2F3AIk1J8VIw4DCrPDXFcFX1dCNMY5MvwWpgi6kQc1/wJLtSuVoMdDRCXC+Pu+xEo4packWdYAqgQEzklURFV6CqIDTtEyVy8WqgEsjZ1VOwx9EkQiholFrypHdxPLCP11EYzQPg6fIYVay7P5kFfFd9yGqj+dmLJGo6W2NUMjvmWYJ4y2ezII+H+TSc3y4R+G6CNu/hSqK4Od8Du9kmEJm6y4NM3Wop9zFXM+WkIUoEPDGbTvkQYPRfprTOWXjic/cOmOLPQloz7/FkGVXEmSe9tvgvCreke+3djtzqB2uZ//UAwf6GEdKFSCfC+pTqMr0HUwmuNCl9U/ebHMyg3rHEiiyjxtPPTUDhjmxHc="
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true






